import { defineConfig } from 'vite'
import { resolve } from 'path'
import fs from 'fs'

// Discover blog post pages (generated by scripts/build-blog.js)
function getBlogInputs() {
  const blogDir = resolve(__dirname, 'blog')
  const inputs = {}
  if (fs.existsSync(resolve(blogDir, 'index.html'))) {
    inputs['blog-index'] = resolve(blogDir, 'index.html')
  }
  if (fs.existsSync(blogDir)) {
    for (const entry of fs.readdirSync(blogDir, { withFileTypes: true })) {
      if (entry.isDirectory() && !entry.name.startsWith('_')) {
        const postIndex = resolve(blogDir, entry.name, 'index.html')
        if (fs.existsSync(postIndex)) {
          inputs[`blog-${entry.name}`] = postIndex
        }
      }
    }
  }
  return inputs
}

export default defineConfig({
  appType: 'mpa',
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        ...getBlogInputs(),
      },
    },
  },
})
